spring.application.name=banking-system-project

# MySQL DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.username=postgres
spring.datasource.password=Ra9841754305!
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties (optional but recommended)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache Configuration
spring.cache.type=redis
spring.cache.cache-names=cache,cache1,cache2
# 1 hour
spring.cache.redis.time-to-live=3600000
spring.cache.redis.cache-null-values=true


management.endpoints.web.exposure.include= *
management.endpoints.health.show-details= always










